name: Docker Build and Publish

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # To add a registry, duplicate this step with registry-specific secrets.
      # Example for GHCR:
      #   - name: Login to GHCR
      #     uses: docker/login-action@v3
      #     with:
      #       registry: ghcr.io
      #       username: ${{ github.actor }}
      #       password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # To publish to additional registries, add their image paths to the
      # `images` list below. Example:
      #   images: |
      #     docker.io/5mdt/mangadex-dl-wui-vibed
      #     ghcr.io/5mdt/mangadex-dl-wui-vibed
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/5mdt/mangadex-dl-wui-vibed
          tags: |
            type=raw,value=release,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag
            type=sha,prefix=sha-,format=short

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PYTHON_VERSION=3.12
